
object BuildDependenciesVersions {
    const val GRADLE_ANDROID = "7.2.1"
    const val KOTLIN = "1.7.10"
    const val NAVIGATION = "2.5.1"
    const val APPCOMPAT = "1.3.1"
    const val MATERIAL = "1.4.0"
    const val LIFECYCLE = "2.5.1"
    const val CORE_KTX = "1.7.0"
    const val ROOM = "2.3.0"
    const val HILT = "2.43.2"
    const val HILT_NAV = "1.0.0"
    const val TIMBER = "5.0.1"
    const val RETROFIT = "2.9.0"
    const val LOGGING = "4.9.2"
    const val MOSHI = "1.14.0"
    const val COROUTINES = "1.5.2"
    const val COIL = "2.2.2"
    const val COMPOSE_COMPILER = "1.3.0"
    const val COMPOSE_RUNTIME = "1.2.1"
    const val COMPOSE_UI = "1.2.1"
    const val COMPOSE_MATERIAL_ICON = "1.2.1"
    const val MATERIAL3 = "1.0.0-alpha05"
    const val CONSTRAIN_LAYOUT = "1.0.0"
    const val ACTIVITY_COMPOSE = "1.5.1"
    const val ACCOMPANIST = "0.23.0"
    const val SKYDOVES = "1.2.3"
    const val CHUCKER = "3.5.2"
    const val CAMERAX = "1.2.0-rc01"
    const val CAMERA_VIEW = "1.0.0-alpha28"
    const val PERMISSION: String = "0.25.1"
    const val COUNTRY_CODE_PICKER: String = "1.1.3"
    const val AUTH_API_PHONE: String = "18.0.1"
    const val ML_TEXT_REC: String = "18.0.1"
    const val FIREBASE_BOM: String = "30.4.1"
    const val APP_DISTRIBUTION = "3.1.0"
    const val NAV_COMPOSE = "2.5.2"
    const val CRASHLYTICS_GRADLE = "2.9.2"
    const val CAMERA_MLKIT = "1.2.0-beta02"
    const val MLKIT_BARCODE = "17.0.2"
    // Tests
    const val TEST = "1.3.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13.1"
    const val MOCKITO = "2.23.0"
    const val ANDROIDX_SPLASH_SCREEN = "1.0.0"
}
